### ISSUE TITLE
syslog errors on running Drop-Down (ubuntu 17.10)

### ISSUE THREAD

**Issue by complete-peacock** [zzrough/gs-extensions-drop-down-terminal#195]
Hi.

Drop-down appears to be working fine on Ubuntu 17.10, but I have noticed the below errors appearing consistently in syslog. FYI

Regards

Oct 21 08:42:29 Tyreus gnome-shell[1257]: JS WARNING: [/home/peacock/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/extension.js 690]: Too many arguments to function GLib.child_watch_add: expected 3, got 4
Oct 21 08:42:29 Tyreus gjs[3600]: JS WARNING: [/home/peacock/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js 615]: Too many arguments to function Gtk.init: expected 1, got 2
Oct 21 08:42:29 Tyreus gjs[3600]: Some code accessed the property 'GTK_VERSION' on the module 'convenience'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Oct 21 08:42:29 Tyreus gjs[3600]: (/build/vte2.91-C4Ziqn/vte2.91-0.48.4/./src/vtegtk.cc:1736):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)
Oct 21 08:42:29 Tyreus gjs[3600]: message repeated 4 times: [ (/build/vte2.91-C4Ziqn/vte2.91-0.48.4/./src/vtegtk.cc:1736):int vte_terminal_match_add_gregex(VteTerminal*, GRegex*, GRegexMatchFlags): runtime check failed: (g_regex_get_compile_flags(gregex) & G_REGEX_MULTILINE)]
