### ISSUE TITLE
Error "terminal.set_background_transparent is not a function" with vte 0.34.8

### ISSUE THREAD

**Issue by phw** [zzrough/gs-extensions-drop-down-terminal#54]
Since I upgraded vte to 0.34.8 on my system I get the following error when opening the dropdown terminal:

```
JS ERROR: !!!   Exception was: TypeError: terminal.set_background_transparent is not a function
JS ERROR: !!!     message = '"terminal.set_background_transparent is not a function"'
JS ERROR: !!!     fileName = '"/home/phw/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js"'
JS ERROR: !!!     lineNumber = '279'
JS ERROR: !!!     stack = '"DropDownTerminal<._createTerminal@/home/phw/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extens...rminal.js:279
wrapper@/usr/share/gjs-1.0/lang.js:213
DropDownTerminal<._init@/home/phw/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js:151
wrapper@/usr/share/gjs-1.0/lang.js:213
_Base._construct@/usr/share/gjs-1.0/lang.js:154
Class._construct/newClass@/usr/share/gjs-1.0/lang.js:248
@/home/phw/.local/share/gnome-shell/extensions/drop-down-terminal@gs-extensions.zzrough.org/terminal.js:543
"'
TypeError: terminal.set_background_transparent is not a function
JS LOG: error: Drop Down Terminal ended abruptly: You can activate the debug mode to nail down the issue
```

Looks like a couple of functions where deprecated, especially `set_background_transparent` and `set_background_image` . See the commit https://git.gnome.org/browse/vte/commit/?h=vte-0-34&id=2da7058c57fd27bb8a8955b50a7a5b2ae8e6d50f

Not sure what the preferred method is to set the opacity now, but `set_color_background_rgba` looks promising.
